# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kannan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/kannan/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kannan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/kannan/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kannan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/kannan/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kannan/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/kannan/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10

In [4]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [5]:
a=arr.size
b=arr.itemsize
print("{} bytes".format(a*b))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
arr =np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


#### 8.  Reverse a vector (first element becomes last)

In [9]:
np.flipud(arr)

array([45, 40, 35, 30, 25, 20, 15, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arr = np.random.randint(0,9,(3,3))
arr

array([[5, 7, 1],
       [8, 5, 0],
       [3, 6, 3]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [13]:
arr= np.array([1,2,0,0,4,0])
ans = np.nonzero(arr)
ans

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [16]:
np.random.random((3,3,3))

array([[[0.5726306 , 0.8188752 , 0.32512838],
        [0.9412166 , 0.10670503, 0.27753024],
        [0.5919785 , 0.31481151, 0.44806639]],

       [[0.84382886, 0.07673178, 0.65158057],
        [0.92763386, 0.36315959, 0.41504586],
        [0.77771102, 0.12393629, 0.93783616]],

       [[0.63155071, 0.43202925, 0.54777683],
        [0.18504548, 0.79590617, 0.82095822],
        [0.40817778, 0.95185032, 0.38841888]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [18]:
arr = np.random.random((10,10))
a= np.max(arr)
b=np.min(arr)
print(a,b,sep="\n")

0.9936090724815517
0.0075657283252379415


#### 14. Create a random vector of size 30 and find the mean value

In [19]:
arr = np.random.random((30))
ans = np.mean(arr)
print(ans)

0.44665258565424415


#### 15. Create a 2d array with 1 on the border and 0 inside

In [20]:
ans = np.ones((5,5))
ans[1:-1,1:-1] = 0
print(ans)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [26]:
ans = np.ones((5,5))
np.pad(ans,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [31]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
ans = np.diag([1,2,3,4],-1)
ans

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [33]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)